import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import '../../../core/widgets/sunya_glass.dart';
import '../domain/appearance_snapshot.dart';
import 'appearance_controller.dart';
class AppearancePage extends ConsumerWidget{const AppearancePage({super.key});
@override Widget build(BuildContext context,WidgetRef ref){final items=ref.watch(appearanceProvider);return Scaffold(appBar:AppBar(title:const Text('Appearance')),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_capture(context,ref),icon:const Icon(Icons.camera_alt_outlined),label:const Text('Daily check-in')),body:ListView(padding:const EdgeInsets.all(20),children:[
Text('Know your face, hair and skin over time.',style:Theme.of(context).textTheme.displaySmall),const SizedBox(height:6),const Text('SUNYA compares consistent photos and self-reported signals. It does not diagnose skin or hair disease.'),const SizedBox(height:20),
SunyaGlassCard(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Daily capture protocol',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:10),const Text('Use the same camera, distance, lighting and neutral expression. Capture front face, hairline and beard area. Avoid filters.'),const SizedBox(height:10),const Text('Track: hairline • density • beard coverage • under-eye appearance • skin clarity',style:TextStyle(fontWeight:FontWeight.w600))])),const SizedBox(height:16),
if(items.isEmpty)const SunyaGlassCard(padding:EdgeInsets.all(20),child:Text('No appearance baseline yet. Take the first controlled photo today.')) else ...items.take(30).map((x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:SunyaGlassCard(padding:const EdgeInsets.all(12),child:Row(children:[SizedBox(width:72,height:72,child:File(x.imagePath).existsSync()?Image.file(File(x.imagePath),fit:BoxFit.cover):const Icon(Icons.image_not_supported_outlined)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.capturedAt.toLocal().toString().split('.').first,style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:5),Text(x.notes.isEmpty?'Controlled appearance snapshot':x.notes),const SizedBox(height:5),Text('Hair ${x.hairDensityScore?.toStringAsFixed(1) ?? '—'}  •  Beard ${x.beardCoverageScore?.toStringAsFixed(1) ?? '—'}  •  Under-eye ${x.underEyeScore?.toStringAsFixed(1) ?? '—'}',style:Theme.of(context).textTheme.bodySmall)]))]))))
]));}
static Future<void> _capture(BuildContext context,WidgetRef ref)async{final source=await showModalBottomSheet<ImageSource>(context:context,builder:(c)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.camera_alt),title:const Text('Camera'),onTap:()=>Navigator.pop(c,ImageSource.camera)),ListTile(leading:const Icon(Icons.photo_library),title:const Text('Gallery'),onTap:()=>Navigator.pop(c,ImageSource.gallery))])));if(source==null)return;final file=await ImagePicker().pickImage(source:source,imageQuality:92);if(file==null)return;await ref.read(appearanceProvider.notifier).add(path:file.path);}
}