import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';
import '../../../core/providers/database_provider.dart';
import '../../../database/local_record_repository.dart';
import '../domain/entities/body_goal.dart';
class BodyGoalsPage extends ConsumerStatefulWidget{const BodyGoalsPage({super.key});@override ConsumerState<BodyGoalsPage> createState()=>_BodyGoalsPageState();}
class _BodyGoalsPageState extends ConsumerState<BodyGoalsPage>{List<BodyGoal> goals=[];static const domain='body_goal';
@override void initState(){super.initState();_load();}
Future<void> _load()async{final r=await ref.read(localRecordRepositoryProvider.future);final x=await r.listDomain(domain);setState(()=>goals=x.map((e)=>BodyGoal.fromJson(Map<String,dynamic>.from(jsonDecode(e.payload) as Map))).toList());}
Future<void> _add()async{final label=TextEditingController(),value=TextEditingController();BodyGoalType type=BodyGoalType.targetWeight;await showDialog(context:context,builder:(d)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Body goal'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<BodyGoalType>(value:type,items:BodyGoalType.values.map((x)=>DropdownMenuItem(value:x,child:Text(x.name))).toList(),onChanged:(x){if(x!=null)set(()=>type=x);}),TextField(controller:label,decoration:const InputDecoration(labelText:'Goal')),TextField(controller:value,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Target value'))]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()async{final v=double.tryParse(value.text);if(v==null)return;final g=BodyGoal(id:const Uuid().v4(),type:type,label:label.text.trim().isEmpty?type.name:label.text.trim(),targetValue:v,unit:type==BodyGoalType.targetWeight?'kg':type==BodyGoalType.targetBodyFat?'%':'cm',createdAt:DateTime.now().toUtc());final r=await ref.read(localRecordRepositoryProvider.future);await r.upsert(domain:domain,key:g.id,payload:g.toJson(),recordDate:g.createdAt);if(mounted)await _load();if(d.mounted)Navigator.pop(d);},child:const Text('Save'))])));label.dispose();value.dispose();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Body goals')),floatingActionButton:FloatingActionButton.extended(onPressed:_add,icon:const Icon(Icons.add),label:const Text('Goal')),body:ListView(padding:const EdgeInsets.all(20),children:[Text('Direction matters.',style:Theme.of(context).textTheme.displaySmall),const SizedBox(height:6),Text('Set measurable body targets.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:20),...goals.map((g)=>Padding(padding:const EdgeInsets.only(bottom:10),child:ListTile(tileColor:Theme.of(context).cardColor,title:Text(g.label),subtitle:Text(g.type.name),trailing:Text(g.targetValue.toStringAsFixed(1)+' '+g.unit))))]);}
}